SELECT 
A."ADMIN",A."SEKSI",A."NAMA_AR",A."BRUTO",
(A."BRUTO"/sum(A."BRUTO") OVER(PARTITION BY A."SEKSI"))*100 AS "KONTRIB_TO_SEKSI",
(A."BRUTO"/sum(A."BRUTO") OVER(PARTITION BY A."ADMIN"))*100 AS "KONTRIB_TO_KANTOR",
(A."BRUTO"/sum(A."BRUTO") OVER())*100 AS "KONTRIB_TO_KANWIL"
FROM (
		SELECT
			p."ADMIN" ,
			p."SEKSI" ,
			p."NAMA_AR" ,
			sum(p."NOMINAL") AS "BRUTO"
		FROM
			ppmpkm p
		WHERE
			p."TAHUNBAYAR" = 2023
			AND p."KET" != 'SPMKP' AND p."ADMIN" != '006'
		GROUP BY
			p."ADMIN" ,
			p."SEKSI" ,
			p."NAMA_AR"
)A
